name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@2aa90cd79663d10959d67faf89a3ecce29392f6a # v2
    with:
      install: true
      test: true
      run-fmt: true

  lint:
    uses: matt-riley/matt-riley-ci/.github/workflows/go-lint.yml@2aa90cd79663d10959d67faf89a3ecce29392f6a # v2

  security:
    uses: matt-riley/matt-riley-ci/.github/workflows/go-security.yml@2aa90cd79663d10959d67faf89a3ecce29392f6a # v2
