name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@9461001818caa7d1925854445cf053d0a0aac316 # v2
    with:
      install: true
      test: true
      run-fmt: true

  lint:
    uses: matt-riley/matt-riley-ci/.github/workflows/go-lint.yml@9461001818caa7d1925854445cf053d0a0aac316 # v2

  security:
    uses: matt-riley/matt-riley-ci/.github/workflows/go-security.yml@9461001818caa7d1925854445cf053d0a0aac316 # v2
