name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@4ff76b1a606b1fbba163119a65bf7b05f91ab9b6 # v3
    with:
      install: true
      test: true
      run-fmt: true

  lint:
    uses: matt-riley/matt-riley-ci/.github/workflows/go-lint.yml@4ff76b1a606b1fbba163119a65bf7b05f91ab9b6 # v3

  security:
    uses: matt-riley/matt-riley-ci/.github/workflows/go-security.yml@4ff76b1a606b1fbba163119a65bf7b05f91ab9b6 # v3
