name: Docker

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    uses: matt-riley/matt-riley-ci/.github/workflows/docker-ghcr-publish.yml@7bf33bf0eef269c4a4b1d85e1668dec14fb8ffff # v1
    with:
      tag-name: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
