name: Docker

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    uses: matt-riley/matt-riley-ci/.github/workflows/docker-ghcr-publish.yml@9461001818caa7d1925854445cf053d0a0aac316 # v2
    with:
      tag-name: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
