name: Docker

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    uses: matt-riley/matt-riley-ci/.github/workflows/docker-ghcr-publish.yml@7fd3aefaab1ae14d063930c85b2d629280c36620 # v2
    with:
      tag-name: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
